/*
 * generated by Xtext 2.37.0
 */
package org.xtext.stlrobust.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.stlrobust.SpecRuntimeModule;
import org.xtext.stlrobust.SpecStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SpecIdeSetup extends SpecStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SpecRuntimeModule(), new SpecIdeModule()));
	}
	
}
