/*
 * generated by Xtext 2.37.0
 */
package org.xtext.stlrobust.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSpecScopeProvider extends DelegatingScopeProvider {
}
