/**
 * generated by Xtext 2.37.0
 */
package org.xtext.stlrobust.spec;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Absence</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.stlrobust.spec.SpecPackage#getAbsence()
 * @model
 * @generated
 */
public interface Absence extends Pattern
{
} // Absence
