/**
 * generated by Xtext 2.37.0
 */
package org.xtext.stlrobust.spec;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>After Scope</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.stlrobust.spec.AfterScope#getQ <em>Q</em>}</li>
 * </ul>
 *
 * @see org.xtext.stlrobust.spec.SpecPackage#getAfterScope()
 * @model
 * @generated
 */
public interface AfterScope extends Scope
{
  /**
   * Returns the value of the '<em><b>Q</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Q</em>' containment reference.
   * @see #setQ(Expression)
   * @see org.xtext.stlrobust.spec.SpecPackage#getAfterScope_Q()
   * @model containment="true"
   * @generated
   */
  Expression getQ();

  /**
   * Sets the value of the '{@link org.xtext.stlrobust.spec.AfterScope#getQ <em>Q</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Q</em>' containment reference.
   * @see #getQ()
   * @generated
   */
  void setQ(Expression value);

} // AfterScope
