/**
 * generated by Xtext 2.37.0
 */
package org.xtext.stlrobust.spec;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Before Scope</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.stlrobust.spec.BeforeScope#getR <em>R</em>}</li>
 * </ul>
 *
 * @see org.xtext.stlrobust.spec.SpecPackage#getBeforeScope()
 * @model
 * @generated
 */
public interface BeforeScope extends Scope
{
  /**
   * Returns the value of the '<em><b>R</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>R</em>' containment reference.
   * @see #setR(Expression)
   * @see org.xtext.stlrobust.spec.SpecPackage#getBeforeScope_R()
   * @model containment="true"
   * @generated
   */
  Expression getR();

  /**
   * Sets the value of the '{@link org.xtext.stlrobust.spec.BeforeScope#getR <em>R</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>R</em>' containment reference.
   * @see #getR()
   * @generated
   */
  void setR(Expression value);

} // BeforeScope
