/**
 * generated by Xtext 2.37.0
 */
package org.xtext.stlrobust.spec;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.stlrobust.spec.Expression#getS1 <em>S1</em>}</li>
 *   <li>{@link org.xtext.stlrobust.spec.Expression#getF1 <em>F1</em>}</li>
 *   <li>{@link org.xtext.stlrobust.spec.Expression#getOperator <em>Operator</em>}</li>
 *   <li>{@link org.xtext.stlrobust.spec.Expression#getS2 <em>S2</em>}</li>
 *   <li>{@link org.xtext.stlrobust.spec.Expression#getF2 <em>F2</em>}</li>
 * </ul>
 *
 * @see org.xtext.stlrobust.spec.SpecPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends EObject
{
  /**
   * Returns the value of the '<em><b>S1</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>S1</em>' reference.
   * @see #setS1(Signal)
   * @see org.xtext.stlrobust.spec.SpecPackage#getExpression_S1()
   * @model
   * @generated
   */
  Signal getS1();

  /**
   * Sets the value of the '{@link org.xtext.stlrobust.spec.Expression#getS1 <em>S1</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>S1</em>' reference.
   * @see #getS1()
   * @generated
   */
  void setS1(Signal value);

  /**
   * Returns the value of the '<em><b>F1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>F1</em>' containment reference.
   * @see #setF1(org.xtext.stlrobust.spec.Number)
   * @see org.xtext.stlrobust.spec.SpecPackage#getExpression_F1()
   * @model containment="true"
   * @generated
   */
  org.xtext.stlrobust.spec.Number getF1();

  /**
   * Sets the value of the '{@link org.xtext.stlrobust.spec.Expression#getF1 <em>F1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>F1</em>' containment reference.
   * @see #getF1()
   * @generated
   */
  void setF1(org.xtext.stlrobust.spec.Number value);

  /**
   * Returns the value of the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' attribute.
   * @see #setOperator(String)
   * @see org.xtext.stlrobust.spec.SpecPackage#getExpression_Operator()
   * @model
   * @generated
   */
  String getOperator();

  /**
   * Sets the value of the '{@link org.xtext.stlrobust.spec.Expression#getOperator <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' attribute.
   * @see #getOperator()
   * @generated
   */
  void setOperator(String value);

  /**
   * Returns the value of the '<em><b>S2</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>S2</em>' reference.
   * @see #setS2(Signal)
   * @see org.xtext.stlrobust.spec.SpecPackage#getExpression_S2()
   * @model
   * @generated
   */
  Signal getS2();

  /**
   * Sets the value of the '{@link org.xtext.stlrobust.spec.Expression#getS2 <em>S2</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>S2</em>' reference.
   * @see #getS2()
   * @generated
   */
  void setS2(Signal value);

  /**
   * Returns the value of the '<em><b>F2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>F2</em>' containment reference.
   * @see #setF2(org.xtext.stlrobust.spec.Number)
   * @see org.xtext.stlrobust.spec.SpecPackage#getExpression_F2()
   * @model containment="true"
   * @generated
   */
  org.xtext.stlrobust.spec.Number getF2();

  /**
   * Sets the value of the '{@link org.xtext.stlrobust.spec.Expression#getF2 <em>F2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>F2</em>' containment reference.
   * @see #getF2()
   * @generated
   */
  void setF2(org.xtext.stlrobust.spec.Number value);

} // Expression
