/**
 * generated by Xtext 2.37.0
 */
package org.xtext.stlrobust.spec;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Global Scope</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.stlrobust.spec.SpecPackage#getGlobalScope()
 * @model
 * @generated
 */
public interface GlobalScope extends Scope
{
} // GlobalScope
