/**
 * generated by Xtext 2.37.0
 */
package org.xtext.stlrobust.spec;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Number</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.stlrobust.spec.Number#getSign <em>Sign</em>}</li>
 *   <li>{@link org.xtext.stlrobust.spec.Number#getIntValue <em>Int Value</em>}</li>
 *   <li>{@link org.xtext.stlrobust.spec.Number#getDecimalValue <em>Decimal Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.stlrobust.spec.SpecPackage#getNumber()
 * @model
 * @generated
 */
public interface Number extends EObject
{
  /**
   * Returns the value of the '<em><b>Sign</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sign</em>' attribute.
   * @see #setSign(String)
   * @see org.xtext.stlrobust.spec.SpecPackage#getNumber_Sign()
   * @model
   * @generated
   */
  String getSign();

  /**
   * Sets the value of the '{@link org.xtext.stlrobust.spec.Number#getSign <em>Sign</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sign</em>' attribute.
   * @see #getSign()
   * @generated
   */
  void setSign(String value);

  /**
   * Returns the value of the '<em><b>Int Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Int Value</em>' attribute.
   * @see #setIntValue(int)
   * @see org.xtext.stlrobust.spec.SpecPackage#getNumber_IntValue()
   * @model
   * @generated
   */
  int getIntValue();

  /**
   * Sets the value of the '{@link org.xtext.stlrobust.spec.Number#getIntValue <em>Int Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Int Value</em>' attribute.
   * @see #getIntValue()
   * @generated
   */
  void setIntValue(int value);

  /**
   * Returns the value of the '<em><b>Decimal Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Decimal Value</em>' attribute.
   * @see #setDecimalValue(int)
   * @see org.xtext.stlrobust.spec.SpecPackage#getNumber_DecimalValue()
   * @model
   * @generated
   */
  int getDecimalValue();

  /**
   * Sets the value of the '{@link org.xtext.stlrobust.spec.Number#getDecimalValue <em>Decimal Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Decimal Value</em>' attribute.
   * @see #getDecimalValue()
   * @generated
   */
  void setDecimalValue(int value);

} // Number
