/**
 * generated by Xtext 2.37.0
 */
package org.xtext.stlrobust.spec;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Response</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.stlrobust.spec.Response#getS <em>S</em>}</li>
 *   <li>{@link org.xtext.stlrobust.spec.Response#getTime <em>Time</em>}</li>
 * </ul>
 *
 * @see org.xtext.stlrobust.spec.SpecPackage#getResponse()
 * @model
 * @generated
 */
public interface Response extends Pattern
{
  /**
   * Returns the value of the '<em><b>S</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>S</em>' containment reference.
   * @see #setS(Expression)
   * @see org.xtext.stlrobust.spec.SpecPackage#getResponse_S()
   * @model containment="true"
   * @generated
   */
  Expression getS();

  /**
   * Sets the value of the '{@link org.xtext.stlrobust.spec.Response#getS <em>S</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>S</em>' containment reference.
   * @see #getS()
   * @generated
   */
  void setS(Expression value);

  /**
   * Returns the value of the '<em><b>Time</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time</em>' containment reference.
   * @see #setTime(Time)
   * @see org.xtext.stlrobust.spec.SpecPackage#getResponse_Time()
   * @model containment="true"
   * @generated
   */
  Time getTime();

  /**
   * Sets the value of the '{@link org.xtext.stlrobust.spec.Response#getTime <em>Time</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time</em>' containment reference.
   * @see #getTime()
   * @generated
   */
  void setTime(Time value);

} // Response
