/**
 * generated by Xtext 2.37.0
 */
package org.xtext.stlrobust.spec;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Scope</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.stlrobust.spec.SpecPackage#getScope()
 * @model
 * @generated
 */
public interface Scope extends EObject
{
} // Scope
