/**
 * generated by Xtext 2.37.0
 */
package org.xtext.stlrobust.spec;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Signal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.stlrobust.spec.Signal#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.stlrobust.spec.Signal#getQueueName <em>Queue Name</em>}</li>
 * </ul>
 *
 * @see org.xtext.stlrobust.spec.SpecPackage#getSignal()
 * @model
 * @generated
 */
public interface Signal extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.stlrobust.spec.SpecPackage#getSignal_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.stlrobust.spec.Signal#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Queue Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Queue Name</em>' attribute.
   * @see #setQueueName(String)
   * @see org.xtext.stlrobust.spec.SpecPackage#getSignal_QueueName()
   * @model
   * @generated
   */
  String getQueueName();

  /**
   * Sets the value of the '{@link org.xtext.stlrobust.spec.Signal#getQueueName <em>Queue Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Queue Name</em>' attribute.
   * @see #getQueueName()
   * @generated
   */
  void setQueueName(String value);

} // Signal
