/**
 * generated by Xtext 2.37.0
 */
package org.xtext.stlrobust.spec;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.stlrobust.spec.SpecFactory
 * @model kind="package"
 * @generated
 */
public interface SpecPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "spec";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/stlrobust/Spec";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "spec";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SpecPackage eINSTANCE = org.xtext.stlrobust.spec.impl.SpecPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.stlrobust.spec.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.stlrobust.spec.impl.ModelImpl
   * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Signals</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__SIGNALS = 0;

  /**
   * The feature id for the '<em><b>Specifications</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__SPECIFICATIONS = 1;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.stlrobust.spec.impl.SignalImpl <em>Signal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.stlrobust.spec.impl.SignalImpl
   * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getSignal()
   * @generated
   */
  int SIGNAL = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIGNAL__NAME = 0;

  /**
   * The feature id for the '<em><b>Queue Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIGNAL__QUEUE_NAME = 1;

  /**
   * The number of structural features of the '<em>Signal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIGNAL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.stlrobust.spec.impl.SpecificationImpl <em>Specification</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.stlrobust.spec.impl.SpecificationImpl
   * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getSpecification()
   * @generated
   */
  int SPECIFICATION = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPECIFICATION__NAME = 0;

  /**
   * The feature id for the '<em><b>Scope</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPECIFICATION__SCOPE = 1;

  /**
   * The feature id for the '<em><b>Pattern</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPECIFICATION__PATTERN = 2;

  /**
   * The number of structural features of the '<em>Specification</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPECIFICATION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.stlrobust.spec.impl.ScopeImpl <em>Scope</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.stlrobust.spec.impl.ScopeImpl
   * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getScope()
   * @generated
   */
  int SCOPE = 3;

  /**
   * The number of structural features of the '<em>Scope</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCOPE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.stlrobust.spec.impl.PatternImpl <em>Pattern</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.stlrobust.spec.impl.PatternImpl
   * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getPattern()
   * @generated
   */
  int PATTERN = 4;

  /**
   * The feature id for the '<em><b>P</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATTERN__P = 0;

  /**
   * The number of structural features of the '<em>Pattern</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATTERN_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.stlrobust.spec.impl.UniversalityImpl <em>Universality</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.stlrobust.spec.impl.UniversalityImpl
   * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getUniversality()
   * @generated
   */
  int UNIVERSALITY = 5;

  /**
   * The feature id for the '<em><b>P</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNIVERSALITY__P = PATTERN__P;

  /**
   * The number of structural features of the '<em>Universality</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNIVERSALITY_FEATURE_COUNT = PATTERN_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.stlrobust.spec.impl.AbsenceImpl <em>Absence</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.stlrobust.spec.impl.AbsenceImpl
   * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getAbsence()
   * @generated
   */
  int ABSENCE = 6;

  /**
   * The feature id for the '<em><b>P</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSENCE__P = PATTERN__P;

  /**
   * The number of structural features of the '<em>Absence</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSENCE_FEATURE_COUNT = PATTERN_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.stlrobust.spec.impl.ExistenceImpl <em>Existence</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.stlrobust.spec.impl.ExistenceImpl
   * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getExistence()
   * @generated
   */
  int EXISTENCE = 7;

  /**
   * The feature id for the '<em><b>P</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXISTENCE__P = PATTERN__P;

  /**
   * The feature id for the '<em><b>Time</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXISTENCE__TIME = PATTERN_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Existence</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXISTENCE_FEATURE_COUNT = PATTERN_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.stlrobust.spec.impl.ResponseImpl <em>Response</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.stlrobust.spec.impl.ResponseImpl
   * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getResponse()
   * @generated
   */
  int RESPONSE = 8;

  /**
   * The feature id for the '<em><b>P</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESPONSE__P = PATTERN__P;

  /**
   * The feature id for the '<em><b>S</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESPONSE__S = PATTERN_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Time</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESPONSE__TIME = PATTERN_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Response</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESPONSE_FEATURE_COUNT = PATTERN_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.stlrobust.spec.impl.NumberImpl <em>Number</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.stlrobust.spec.impl.NumberImpl
   * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getNumber()
   * @generated
   */
  int NUMBER = 9;

  /**
   * The feature id for the '<em><b>Sign</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER__SIGN = 0;

  /**
   * The feature id for the '<em><b>Int Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER__INT_VALUE = 1;

  /**
   * The feature id for the '<em><b>Decimal Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER__DECIMAL_VALUE = 2;

  /**
   * The number of structural features of the '<em>Number</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.stlrobust.spec.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.stlrobust.spec.impl.ExpressionImpl
   * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 10;

  /**
   * The feature id for the '<em><b>S1</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__S1 = 0;

  /**
   * The feature id for the '<em><b>F1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__F1 = 1;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__OPERATOR = 2;

  /**
   * The feature id for the '<em><b>S2</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__S2 = 3;

  /**
   * The feature id for the '<em><b>F2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__F2 = 4;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.stlrobust.spec.impl.TimeImpl <em>Time</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.stlrobust.spec.impl.TimeImpl
   * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getTime()
   * @generated
   */
  int TIME = 11;

  /**
   * The feature id for the '<em><b>Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME__UNIT = 0;

  /**
   * The number of structural features of the '<em>Time</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.stlrobust.spec.impl.UpperTimeBoundImpl <em>Upper Time Bound</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.stlrobust.spec.impl.UpperTimeBoundImpl
   * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getUpperTimeBound()
   * @generated
   */
  int UPPER_TIME_BOUND = 12;

  /**
   * The feature id for the '<em><b>Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UPPER_TIME_BOUND__UNIT = TIME__UNIT;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UPPER_TIME_BOUND__VALUE = TIME_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Upper Time Bound</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UPPER_TIME_BOUND_FEATURE_COUNT = TIME_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.stlrobust.spec.impl.LowerTimeBoundImpl <em>Lower Time Bound</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.stlrobust.spec.impl.LowerTimeBoundImpl
   * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getLowerTimeBound()
   * @generated
   */
  int LOWER_TIME_BOUND = 13;

  /**
   * The feature id for the '<em><b>Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOWER_TIME_BOUND__UNIT = TIME__UNIT;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOWER_TIME_BOUND__VALUE = TIME_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Lower Time Bound</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOWER_TIME_BOUND_FEATURE_COUNT = TIME_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.stlrobust.spec.impl.IntervalImpl <em>Interval</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.stlrobust.spec.impl.IntervalImpl
   * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getInterval()
   * @generated
   */
  int INTERVAL = 14;

  /**
   * The feature id for the '<em><b>Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERVAL__UNIT = TIME__UNIT;

  /**
   * The feature id for the '<em><b>Min</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERVAL__MIN = TIME_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Max</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERVAL__MAX = TIME_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Interval</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTERVAL_FEATURE_COUNT = TIME_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.stlrobust.spec.impl.GlobalScopeImpl <em>Global Scope</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.stlrobust.spec.impl.GlobalScopeImpl
   * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getGlobalScope()
   * @generated
   */
  int GLOBAL_SCOPE = 15;

  /**
   * The number of structural features of the '<em>Global Scope</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GLOBAL_SCOPE_FEATURE_COUNT = SCOPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.stlrobust.spec.impl.BeforeScopeImpl <em>Before Scope</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.stlrobust.spec.impl.BeforeScopeImpl
   * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getBeforeScope()
   * @generated
   */
  int BEFORE_SCOPE = 16;

  /**
   * The feature id for the '<em><b>R</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEFORE_SCOPE__R = SCOPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Before Scope</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEFORE_SCOPE_FEATURE_COUNT = SCOPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.stlrobust.spec.impl.AfterScopeImpl <em>After Scope</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.stlrobust.spec.impl.AfterScopeImpl
   * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getAfterScope()
   * @generated
   */
  int AFTER_SCOPE = 17;

  /**
   * The feature id for the '<em><b>Q</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AFTER_SCOPE__Q = SCOPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>After Scope</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AFTER_SCOPE_FEATURE_COUNT = SCOPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.stlrobust.spec.impl.BetweenScopeImpl <em>Between Scope</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.stlrobust.spec.impl.BetweenScopeImpl
   * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getBetweenScope()
   * @generated
   */
  int BETWEEN_SCOPE = 18;

  /**
   * The feature id for the '<em><b>Q</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BETWEEN_SCOPE__Q = SCOPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>R</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BETWEEN_SCOPE__R = SCOPE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Between Scope</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BETWEEN_SCOPE_FEATURE_COUNT = SCOPE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.stlrobust.spec.impl.AfterUntilScopeImpl <em>After Until Scope</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.stlrobust.spec.impl.AfterUntilScopeImpl
   * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getAfterUntilScope()
   * @generated
   */
  int AFTER_UNTIL_SCOPE = 19;

  /**
   * The feature id for the '<em><b>Q</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AFTER_UNTIL_SCOPE__Q = SCOPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>R</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AFTER_UNTIL_SCOPE__R = SCOPE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>After Until Scope</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AFTER_UNTIL_SCOPE_FEATURE_COUNT = SCOPE_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link org.xtext.stlrobust.spec.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.stlrobust.spec.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.stlrobust.spec.Model#getSignals <em>Signals</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Signals</em>'.
   * @see org.xtext.stlrobust.spec.Model#getSignals()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Signals();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.stlrobust.spec.Model#getSpecifications <em>Specifications</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Specifications</em>'.
   * @see org.xtext.stlrobust.spec.Model#getSpecifications()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Specifications();

  /**
   * Returns the meta object for class '{@link org.xtext.stlrobust.spec.Signal <em>Signal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Signal</em>'.
   * @see org.xtext.stlrobust.spec.Signal
   * @generated
   */
  EClass getSignal();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.stlrobust.spec.Signal#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.stlrobust.spec.Signal#getName()
   * @see #getSignal()
   * @generated
   */
  EAttribute getSignal_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.stlrobust.spec.Signal#getQueueName <em>Queue Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Queue Name</em>'.
   * @see org.xtext.stlrobust.spec.Signal#getQueueName()
   * @see #getSignal()
   * @generated
   */
  EAttribute getSignal_QueueName();

  /**
   * Returns the meta object for class '{@link org.xtext.stlrobust.spec.Specification <em>Specification</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Specification</em>'.
   * @see org.xtext.stlrobust.spec.Specification
   * @generated
   */
  EClass getSpecification();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.stlrobust.spec.Specification#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.stlrobust.spec.Specification#getName()
   * @see #getSpecification()
   * @generated
   */
  EAttribute getSpecification_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.stlrobust.spec.Specification#getScope <em>Scope</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Scope</em>'.
   * @see org.xtext.stlrobust.spec.Specification#getScope()
   * @see #getSpecification()
   * @generated
   */
  EReference getSpecification_Scope();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.stlrobust.spec.Specification#getPattern <em>Pattern</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Pattern</em>'.
   * @see org.xtext.stlrobust.spec.Specification#getPattern()
   * @see #getSpecification()
   * @generated
   */
  EReference getSpecification_Pattern();

  /**
   * Returns the meta object for class '{@link org.xtext.stlrobust.spec.Scope <em>Scope</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Scope</em>'.
   * @see org.xtext.stlrobust.spec.Scope
   * @generated
   */
  EClass getScope();

  /**
   * Returns the meta object for class '{@link org.xtext.stlrobust.spec.Pattern <em>Pattern</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pattern</em>'.
   * @see org.xtext.stlrobust.spec.Pattern
   * @generated
   */
  EClass getPattern();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.stlrobust.spec.Pattern#getP <em>P</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>P</em>'.
   * @see org.xtext.stlrobust.spec.Pattern#getP()
   * @see #getPattern()
   * @generated
   */
  EReference getPattern_P();

  /**
   * Returns the meta object for class '{@link org.xtext.stlrobust.spec.Universality <em>Universality</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Universality</em>'.
   * @see org.xtext.stlrobust.spec.Universality
   * @generated
   */
  EClass getUniversality();

  /**
   * Returns the meta object for class '{@link org.xtext.stlrobust.spec.Absence <em>Absence</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Absence</em>'.
   * @see org.xtext.stlrobust.spec.Absence
   * @generated
   */
  EClass getAbsence();

  /**
   * Returns the meta object for class '{@link org.xtext.stlrobust.spec.Existence <em>Existence</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Existence</em>'.
   * @see org.xtext.stlrobust.spec.Existence
   * @generated
   */
  EClass getExistence();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.stlrobust.spec.Existence#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Time</em>'.
   * @see org.xtext.stlrobust.spec.Existence#getTime()
   * @see #getExistence()
   * @generated
   */
  EReference getExistence_Time();

  /**
   * Returns the meta object for class '{@link org.xtext.stlrobust.spec.Response <em>Response</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Response</em>'.
   * @see org.xtext.stlrobust.spec.Response
   * @generated
   */
  EClass getResponse();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.stlrobust.spec.Response#getS <em>S</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>S</em>'.
   * @see org.xtext.stlrobust.spec.Response#getS()
   * @see #getResponse()
   * @generated
   */
  EReference getResponse_S();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.stlrobust.spec.Response#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Time</em>'.
   * @see org.xtext.stlrobust.spec.Response#getTime()
   * @see #getResponse()
   * @generated
   */
  EReference getResponse_Time();

  /**
   * Returns the meta object for class '{@link org.xtext.stlrobust.spec.Number <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Number</em>'.
   * @see org.xtext.stlrobust.spec.Number
   * @generated
   */
  EClass getNumber();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.stlrobust.spec.Number#getSign <em>Sign</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sign</em>'.
   * @see org.xtext.stlrobust.spec.Number#getSign()
   * @see #getNumber()
   * @generated
   */
  EAttribute getNumber_Sign();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.stlrobust.spec.Number#getIntValue <em>Int Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Int Value</em>'.
   * @see org.xtext.stlrobust.spec.Number#getIntValue()
   * @see #getNumber()
   * @generated
   */
  EAttribute getNumber_IntValue();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.stlrobust.spec.Number#getDecimalValue <em>Decimal Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Decimal Value</em>'.
   * @see org.xtext.stlrobust.spec.Number#getDecimalValue()
   * @see #getNumber()
   * @generated
   */
  EAttribute getNumber_DecimalValue();

  /**
   * Returns the meta object for class '{@link org.xtext.stlrobust.spec.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see org.xtext.stlrobust.spec.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for the reference '{@link org.xtext.stlrobust.spec.Expression#getS1 <em>S1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>S1</em>'.
   * @see org.xtext.stlrobust.spec.Expression#getS1()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_S1();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.stlrobust.spec.Expression#getF1 <em>F1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>F1</em>'.
   * @see org.xtext.stlrobust.spec.Expression#getF1()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_F1();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.stlrobust.spec.Expression#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see org.xtext.stlrobust.spec.Expression#getOperator()
   * @see #getExpression()
   * @generated
   */
  EAttribute getExpression_Operator();

  /**
   * Returns the meta object for the reference '{@link org.xtext.stlrobust.spec.Expression#getS2 <em>S2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>S2</em>'.
   * @see org.xtext.stlrobust.spec.Expression#getS2()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_S2();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.stlrobust.spec.Expression#getF2 <em>F2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>F2</em>'.
   * @see org.xtext.stlrobust.spec.Expression#getF2()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_F2();

  /**
   * Returns the meta object for class '{@link org.xtext.stlrobust.spec.Time <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Time</em>'.
   * @see org.xtext.stlrobust.spec.Time
   * @generated
   */
  EClass getTime();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.stlrobust.spec.Time#getUnit <em>Unit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Unit</em>'.
   * @see org.xtext.stlrobust.spec.Time#getUnit()
   * @see #getTime()
   * @generated
   */
  EAttribute getTime_Unit();

  /**
   * Returns the meta object for class '{@link org.xtext.stlrobust.spec.UpperTimeBound <em>Upper Time Bound</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Upper Time Bound</em>'.
   * @see org.xtext.stlrobust.spec.UpperTimeBound
   * @generated
   */
  EClass getUpperTimeBound();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.stlrobust.spec.UpperTimeBound#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.stlrobust.spec.UpperTimeBound#getValue()
   * @see #getUpperTimeBound()
   * @generated
   */
  EAttribute getUpperTimeBound_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.stlrobust.spec.LowerTimeBound <em>Lower Time Bound</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lower Time Bound</em>'.
   * @see org.xtext.stlrobust.spec.LowerTimeBound
   * @generated
   */
  EClass getLowerTimeBound();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.stlrobust.spec.LowerTimeBound#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.stlrobust.spec.LowerTimeBound#getValue()
   * @see #getLowerTimeBound()
   * @generated
   */
  EAttribute getLowerTimeBound_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.stlrobust.spec.Interval <em>Interval</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Interval</em>'.
   * @see org.xtext.stlrobust.spec.Interval
   * @generated
   */
  EClass getInterval();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.stlrobust.spec.Interval#getMin <em>Min</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Min</em>'.
   * @see org.xtext.stlrobust.spec.Interval#getMin()
   * @see #getInterval()
   * @generated
   */
  EAttribute getInterval_Min();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.stlrobust.spec.Interval#getMax <em>Max</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Max</em>'.
   * @see org.xtext.stlrobust.spec.Interval#getMax()
   * @see #getInterval()
   * @generated
   */
  EAttribute getInterval_Max();

  /**
   * Returns the meta object for class '{@link org.xtext.stlrobust.spec.GlobalScope <em>Global Scope</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Global Scope</em>'.
   * @see org.xtext.stlrobust.spec.GlobalScope
   * @generated
   */
  EClass getGlobalScope();

  /**
   * Returns the meta object for class '{@link org.xtext.stlrobust.spec.BeforeScope <em>Before Scope</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Before Scope</em>'.
   * @see org.xtext.stlrobust.spec.BeforeScope
   * @generated
   */
  EClass getBeforeScope();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.stlrobust.spec.BeforeScope#getR <em>R</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>R</em>'.
   * @see org.xtext.stlrobust.spec.BeforeScope#getR()
   * @see #getBeforeScope()
   * @generated
   */
  EReference getBeforeScope_R();

  /**
   * Returns the meta object for class '{@link org.xtext.stlrobust.spec.AfterScope <em>After Scope</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>After Scope</em>'.
   * @see org.xtext.stlrobust.spec.AfterScope
   * @generated
   */
  EClass getAfterScope();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.stlrobust.spec.AfterScope#getQ <em>Q</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Q</em>'.
   * @see org.xtext.stlrobust.spec.AfterScope#getQ()
   * @see #getAfterScope()
   * @generated
   */
  EReference getAfterScope_Q();

  /**
   * Returns the meta object for class '{@link org.xtext.stlrobust.spec.BetweenScope <em>Between Scope</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Between Scope</em>'.
   * @see org.xtext.stlrobust.spec.BetweenScope
   * @generated
   */
  EClass getBetweenScope();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.stlrobust.spec.BetweenScope#getQ <em>Q</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Q</em>'.
   * @see org.xtext.stlrobust.spec.BetweenScope#getQ()
   * @see #getBetweenScope()
   * @generated
   */
  EReference getBetweenScope_Q();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.stlrobust.spec.BetweenScope#getR <em>R</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>R</em>'.
   * @see org.xtext.stlrobust.spec.BetweenScope#getR()
   * @see #getBetweenScope()
   * @generated
   */
  EReference getBetweenScope_R();

  /**
   * Returns the meta object for class '{@link org.xtext.stlrobust.spec.AfterUntilScope <em>After Until Scope</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>After Until Scope</em>'.
   * @see org.xtext.stlrobust.spec.AfterUntilScope
   * @generated
   */
  EClass getAfterUntilScope();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.stlrobust.spec.AfterUntilScope#getQ <em>Q</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Q</em>'.
   * @see org.xtext.stlrobust.spec.AfterUntilScope#getQ()
   * @see #getAfterUntilScope()
   * @generated
   */
  EReference getAfterUntilScope_Q();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.stlrobust.spec.AfterUntilScope#getR <em>R</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>R</em>'.
   * @see org.xtext.stlrobust.spec.AfterUntilScope#getR()
   * @see #getAfterUntilScope()
   * @generated
   */
  EReference getAfterUntilScope_R();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SpecFactory getSpecFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.stlrobust.spec.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.stlrobust.spec.impl.ModelImpl
     * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Signals</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__SIGNALS = eINSTANCE.getModel_Signals();

    /**
     * The meta object literal for the '<em><b>Specifications</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__SPECIFICATIONS = eINSTANCE.getModel_Specifications();

    /**
     * The meta object literal for the '{@link org.xtext.stlrobust.spec.impl.SignalImpl <em>Signal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.stlrobust.spec.impl.SignalImpl
     * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getSignal()
     * @generated
     */
    EClass SIGNAL = eINSTANCE.getSignal();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIGNAL__NAME = eINSTANCE.getSignal_Name();

    /**
     * The meta object literal for the '<em><b>Queue Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIGNAL__QUEUE_NAME = eINSTANCE.getSignal_QueueName();

    /**
     * The meta object literal for the '{@link org.xtext.stlrobust.spec.impl.SpecificationImpl <em>Specification</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.stlrobust.spec.impl.SpecificationImpl
     * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getSpecification()
     * @generated
     */
    EClass SPECIFICATION = eINSTANCE.getSpecification();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SPECIFICATION__NAME = eINSTANCE.getSpecification_Name();

    /**
     * The meta object literal for the '<em><b>Scope</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SPECIFICATION__SCOPE = eINSTANCE.getSpecification_Scope();

    /**
     * The meta object literal for the '<em><b>Pattern</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SPECIFICATION__PATTERN = eINSTANCE.getSpecification_Pattern();

    /**
     * The meta object literal for the '{@link org.xtext.stlrobust.spec.impl.ScopeImpl <em>Scope</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.stlrobust.spec.impl.ScopeImpl
     * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getScope()
     * @generated
     */
    EClass SCOPE = eINSTANCE.getScope();

    /**
     * The meta object literal for the '{@link org.xtext.stlrobust.spec.impl.PatternImpl <em>Pattern</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.stlrobust.spec.impl.PatternImpl
     * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getPattern()
     * @generated
     */
    EClass PATTERN = eINSTANCE.getPattern();

    /**
     * The meta object literal for the '<em><b>P</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PATTERN__P = eINSTANCE.getPattern_P();

    /**
     * The meta object literal for the '{@link org.xtext.stlrobust.spec.impl.UniversalityImpl <em>Universality</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.stlrobust.spec.impl.UniversalityImpl
     * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getUniversality()
     * @generated
     */
    EClass UNIVERSALITY = eINSTANCE.getUniversality();

    /**
     * The meta object literal for the '{@link org.xtext.stlrobust.spec.impl.AbsenceImpl <em>Absence</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.stlrobust.spec.impl.AbsenceImpl
     * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getAbsence()
     * @generated
     */
    EClass ABSENCE = eINSTANCE.getAbsence();

    /**
     * The meta object literal for the '{@link org.xtext.stlrobust.spec.impl.ExistenceImpl <em>Existence</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.stlrobust.spec.impl.ExistenceImpl
     * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getExistence()
     * @generated
     */
    EClass EXISTENCE = eINSTANCE.getExistence();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXISTENCE__TIME = eINSTANCE.getExistence_Time();

    /**
     * The meta object literal for the '{@link org.xtext.stlrobust.spec.impl.ResponseImpl <em>Response</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.stlrobust.spec.impl.ResponseImpl
     * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getResponse()
     * @generated
     */
    EClass RESPONSE = eINSTANCE.getResponse();

    /**
     * The meta object literal for the '<em><b>S</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RESPONSE__S = eINSTANCE.getResponse_S();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RESPONSE__TIME = eINSTANCE.getResponse_Time();

    /**
     * The meta object literal for the '{@link org.xtext.stlrobust.spec.impl.NumberImpl <em>Number</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.stlrobust.spec.impl.NumberImpl
     * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getNumber()
     * @generated
     */
    EClass NUMBER = eINSTANCE.getNumber();

    /**
     * The meta object literal for the '<em><b>Sign</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUMBER__SIGN = eINSTANCE.getNumber_Sign();

    /**
     * The meta object literal for the '<em><b>Int Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUMBER__INT_VALUE = eINSTANCE.getNumber_IntValue();

    /**
     * The meta object literal for the '<em><b>Decimal Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUMBER__DECIMAL_VALUE = eINSTANCE.getNumber_DecimalValue();

    /**
     * The meta object literal for the '{@link org.xtext.stlrobust.spec.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.stlrobust.spec.impl.ExpressionImpl
     * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '<em><b>S1</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__S1 = eINSTANCE.getExpression_S1();

    /**
     * The meta object literal for the '<em><b>F1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__F1 = eINSTANCE.getExpression_F1();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION__OPERATOR = eINSTANCE.getExpression_Operator();

    /**
     * The meta object literal for the '<em><b>S2</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__S2 = eINSTANCE.getExpression_S2();

    /**
     * The meta object literal for the '<em><b>F2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__F2 = eINSTANCE.getExpression_F2();

    /**
     * The meta object literal for the '{@link org.xtext.stlrobust.spec.impl.TimeImpl <em>Time</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.stlrobust.spec.impl.TimeImpl
     * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getTime()
     * @generated
     */
    EClass TIME = eINSTANCE.getTime();

    /**
     * The meta object literal for the '<em><b>Unit</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIME__UNIT = eINSTANCE.getTime_Unit();

    /**
     * The meta object literal for the '{@link org.xtext.stlrobust.spec.impl.UpperTimeBoundImpl <em>Upper Time Bound</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.stlrobust.spec.impl.UpperTimeBoundImpl
     * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getUpperTimeBound()
     * @generated
     */
    EClass UPPER_TIME_BOUND = eINSTANCE.getUpperTimeBound();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UPPER_TIME_BOUND__VALUE = eINSTANCE.getUpperTimeBound_Value();

    /**
     * The meta object literal for the '{@link org.xtext.stlrobust.spec.impl.LowerTimeBoundImpl <em>Lower Time Bound</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.stlrobust.spec.impl.LowerTimeBoundImpl
     * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getLowerTimeBound()
     * @generated
     */
    EClass LOWER_TIME_BOUND = eINSTANCE.getLowerTimeBound();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOWER_TIME_BOUND__VALUE = eINSTANCE.getLowerTimeBound_Value();

    /**
     * The meta object literal for the '{@link org.xtext.stlrobust.spec.impl.IntervalImpl <em>Interval</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.stlrobust.spec.impl.IntervalImpl
     * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getInterval()
     * @generated
     */
    EClass INTERVAL = eINSTANCE.getInterval();

    /**
     * The meta object literal for the '<em><b>Min</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTERVAL__MIN = eINSTANCE.getInterval_Min();

    /**
     * The meta object literal for the '<em><b>Max</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INTERVAL__MAX = eINSTANCE.getInterval_Max();

    /**
     * The meta object literal for the '{@link org.xtext.stlrobust.spec.impl.GlobalScopeImpl <em>Global Scope</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.stlrobust.spec.impl.GlobalScopeImpl
     * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getGlobalScope()
     * @generated
     */
    EClass GLOBAL_SCOPE = eINSTANCE.getGlobalScope();

    /**
     * The meta object literal for the '{@link org.xtext.stlrobust.spec.impl.BeforeScopeImpl <em>Before Scope</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.stlrobust.spec.impl.BeforeScopeImpl
     * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getBeforeScope()
     * @generated
     */
    EClass BEFORE_SCOPE = eINSTANCE.getBeforeScope();

    /**
     * The meta object literal for the '<em><b>R</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BEFORE_SCOPE__R = eINSTANCE.getBeforeScope_R();

    /**
     * The meta object literal for the '{@link org.xtext.stlrobust.spec.impl.AfterScopeImpl <em>After Scope</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.stlrobust.spec.impl.AfterScopeImpl
     * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getAfterScope()
     * @generated
     */
    EClass AFTER_SCOPE = eINSTANCE.getAfterScope();

    /**
     * The meta object literal for the '<em><b>Q</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AFTER_SCOPE__Q = eINSTANCE.getAfterScope_Q();

    /**
     * The meta object literal for the '{@link org.xtext.stlrobust.spec.impl.BetweenScopeImpl <em>Between Scope</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.stlrobust.spec.impl.BetweenScopeImpl
     * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getBetweenScope()
     * @generated
     */
    EClass BETWEEN_SCOPE = eINSTANCE.getBetweenScope();

    /**
     * The meta object literal for the '<em><b>Q</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BETWEEN_SCOPE__Q = eINSTANCE.getBetweenScope_Q();

    /**
     * The meta object literal for the '<em><b>R</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BETWEEN_SCOPE__R = eINSTANCE.getBetweenScope_R();

    /**
     * The meta object literal for the '{@link org.xtext.stlrobust.spec.impl.AfterUntilScopeImpl <em>After Until Scope</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.stlrobust.spec.impl.AfterUntilScopeImpl
     * @see org.xtext.stlrobust.spec.impl.SpecPackageImpl#getAfterUntilScope()
     * @generated
     */
    EClass AFTER_UNTIL_SCOPE = eINSTANCE.getAfterUntilScope();

    /**
     * The meta object literal for the '<em><b>Q</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AFTER_UNTIL_SCOPE__Q = eINSTANCE.getAfterUntilScope_Q();

    /**
     * The meta object literal for the '<em><b>R</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AFTER_UNTIL_SCOPE__R = eINSTANCE.getAfterUntilScope_R();

  }

} //SpecPackage
