/**
 * generated by Xtext 2.37.0
 */
package org.xtext.stlrobust.spec;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Upper Time Bound</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.stlrobust.spec.UpperTimeBound#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.stlrobust.spec.SpecPackage#getUpperTimeBound()
 * @model
 * @generated
 */
public interface UpperTimeBound extends Time
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(int)
   * @see org.xtext.stlrobust.spec.SpecPackage#getUpperTimeBound_Value()
   * @model
   * @generated
   */
  int getValue();

  /**
   * Sets the value of the '{@link org.xtext.stlrobust.spec.UpperTimeBound#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(int value);

} // UpperTimeBound
