/**
 * generated by Xtext 2.37.0
 */
package org.xtext.stlrobust.spec.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.stlrobust.spec.Absence;
import org.xtext.stlrobust.spec.SpecPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Absence</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AbsenceImpl extends PatternImpl implements Absence
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AbsenceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SpecPackage.Literals.ABSENCE;
  }

} //AbsenceImpl
