/**
 * generated by Xtext 2.37.0
 */
package org.xtext.stlrobust.spec.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.stlrobust.spec.SpecPackage;
import org.xtext.stlrobust.spec.Universality;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Universality</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class UniversalityImpl extends PatternImpl implements Universality
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UniversalityImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SpecPackage.Literals.UNIVERSALITY;
  }

} //UniversalityImpl
