/*
 * generated by Xtext 2.37.0
 */
package org.xtext.stlrobust.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SpecUiModule extends AbstractSpecUiModule {

	public SpecUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
