/*
 * generated by Xtext 2.37.0
 */
package org.xtext.stlrobust.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.stlrobust.spec.ui.internal.SpecActivator;

public class SpecUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SpecActivator.getInstance().getInjector("org.xtext.stlrobust.Spec");
	}

}
