/*
 * generated by Xtext 2.37.0
 */
package org.xtext.stlrobust.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link SpecWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractSpecWebModule extends DefaultWebModule {

}
