/*
 * generated by Xtext 2.37.0
 */
package org.xtext.stlrobust;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SpecStandaloneSetup extends SpecStandaloneSetupGenerated {

	public static void doSetup() {
		new SpecStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
