/*
 * generated by Xtext 2.37.0
 */
package org.xtext.stlrobust.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.stlrobust.spec.ui.internal.SpecActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SpecExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(SpecActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		SpecActivator activator = SpecActivator.getInstance();
		return activator != null ? activator.getInjector(SpecActivator.ORG_XTEXT_STLROBUST_SPEC) : null;
	}

}
