/*
 * generated by Xtext 2.37.0
 */
package org.xtext.stlrobust.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class SpecWebModule extends AbstractSpecWebModule {
}
